#=============关节限制===============

# 全局缩放因子（  Max = 1 )
#！！！！！！是全局！！！！！！
default_velocity_scaling_factor: 0.5
default_acceleration_scaling_factor: 0.5

# 每个关节的具体限制
joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 3.0                       # 最大速度 (rad/s)
    has_acceleration_limits: true
    max_acceleration: 5.0                   # 最大加速度 (rad/s²)
  
  joint2:                       
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  
  joint3:                       
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: true
    max_acceleration: 5.0
    min_position: -1.5708
    max_position: 4.7124  
  
  joint4:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 15.0
